- name: Is Code Already installed?
  shell: which code
  register: which
  changed_when: false
  failed_when: false

- include_tasks: "{{ ansible_os_family }}/{{ ansible_distribution }}/main.yml"
  when: not which.rc == 0
